### ISSUE TITLE
Option of returning object

### ISSUE THREAD

**Issue by fabiancook** [yoshuawuyts/nanographql#5]
I've been using this module where I can inject a couple of variables before sending it off to the server, would be great to be able to do this without first parsing the output, then using stringify again. 

Return string by default, but object if requested?

**Comment by yoshuawuyts** [comment]
Yeah, could do! - what kind of vars do you tend to inject?

**Comment by fabiancook** [comment]
Common identity tokens, I’m probably doing it the wrong way, but usually will just add it into any request to the graphql server on the variables object
