### ISSUE TITLE
Remove experimental label?

### ISSUE THREAD

**Issue by fabiancook** [yoshuawuyts/nanographql#9]
I've been using this in production for a good amount of time now in a few different projects, does its job exactly right, has a 2.0.0 release, feel like it could be relabeled so it's not just seen as experimental anymore. 

It has the most stable API I have ever seen 👌

**Comment by yoshuawuyts** [comment]
Hah, yay! -- glad you like it. Yeah up for changing the label. Would you like to PR it?
